### ISSUE TITLE
Poll: why are you using argparse from pypi (or from here) these days?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ThomasWaldmann/argparse#100]
Just wondering:

Considering that everybody should use py27 or py34+ these days (which all have argparse built-in), I am wondering why people keep starring this repository on github.

Do you still use this? Why? Please leave comments below.

Some stats: https://libraries.io/pypi/argparse

**Comment by jwilk** [comment]
Some long-term support distros (RHEL 6, SLES 11) ship with Python 2.6, so I continue to support this version in my Python 2.X programs when that's not too onerous.
I use argparse from PyPI to test if my programs still work with Python 2.6.

**Comment by ThomasWaldmann** [comment]
ah, right. thanks for explaining.

**Comment by ThomasWaldmann** [comment]
Considering all python versions addressed by this code (see README) are out of support, I will archive this repo now.
