### ISSUE TITLE
parsing only a subset and leave all other checks undone

### ISSUE THREAD

**Issue by hivemall** [ThomasWaldmann/argparse#103]
i try to extract just one optional arg also other nonoptionals might not have been supplied:

```
import argparse
parser.add_argument('d', help='dunt')
parser.add_argument('-c', help='copper')
args = parser.parse_known_args(args=['-c'])
 
usage: main.py [-h] [-c C] d
main.py: error: argument -c: expected one argument
```

It should only extract -c and leave d alone. I try to put -c into an external file which should silently do its thing without other arg checking , in this case 'd'. Why even throw on optional here.

violating the doc?
> that it does not produce an error when extra arguments are present.

now if i try 
```

parser.add_argument('-c', help='copper')
args = parser.parse_known_args(args=['-c'])
```
it throws on an optional one, shouldnt since c=None then

**Comment by ThomasWaldmann** [comment]
https://github.com/ThomasWaldmann/argparse/blob/master/README.txt

did you read this? closing.

**Comment by hivemall** [comment]
Yes i did now, so file a bug report for the lib maintainers?

**Comment by ThomasWaldmann** [comment]
i didn't analyze your bug report, this is the wrong place in any case.

either ask on the python support channels or directly file a bug, if you are confident it is one.
