### ISSUE TITLE
Argparse 1.4.0 doesn't have a wheel on PyPI: causes get-pip.py failures.

### ISSUE THREAD

**Issue by nedbat** [ThomasWaldmann/argparse#91]
If you could upload a .whl file for 1.4.0, it would solve some problems.  get-pip.py depends on wheel, which depends on argparse on Python 2.6.  get-pip.py tries to install wheels, and without an argparse 1.4.0 wheel, it fails.  See line 36 here:  https://ci.appveyor.com/project/nedbat/coveragepy/build/default-98/job/tr3r2eejjdsslnwm

Thanks.

**Comment by nedbat** [comment]
cc @dstufft

**Comment by ThomasWaldmann** [comment]
fixed, thanks for the hint.
