### ISSUE TITLE
Is " if option_string.startswith(option_prefix): " a special design in _get_option_tuples()?

### ISSUE THREAD

**Issue by dongdxf** [ThomasWaldmann/argparse#93]
the help of my script is:
test.py config {--list | --list-all}
--list       list configurations from a specified file
--list-all  list all effective configurations

" test.py config --list " is ok.
but,
" test.py config --list- ",
" test.py config --list-a ",
" test.py config --list-al ",
" test.py config --list-all ",
they are all equivalent.

i debuged it using pdb, and got:
" if option_string.startswith(option_prefix): " in _get_option_tuples().

is this a special design？

thanks.

**Comment by ThomasWaldmann** [comment]
@dongdxf if you can reproduce this with argparse from stdlib (just try with a recent python version, 2.7.x or 3.4.x), this might be something that should go into python's main issue tracker rather than into here.

**Comment by dongdxf** [comment]
thanks for your reply.

i can reproduce it with argparse from stdlib (2.7.10 and 3.5.0), and argparse.py from PyPI.

**Comment by ThomasWaldmann** [comment]
OK, then please file an issue in the main python issue tracker (most argparse development happens there, the pypi argparse [and this repo] is just an extracted version of it, mostly for python 2.6 users, when argparse was not available from stdlib).
