### ISSUE TITLE
argparse WBN if default values displayed in -h message

### ISSUE THREAD

**Issue by jrbrearley** [ThomasWaldmann/argparse#98]
When you define the parser arguments, you usually define the default values, as shown below. When the user specifies '-h' on the command line, or makes a typo, the message you get shows the correct spelling of the options but not the default values. Showing the actual numeric (or string) default values would be a lot more useful than showing the uppercase name of the option.

parser.add_argument('--batch_size', default=100, type=int, help='batch size')

I am using Python 3.6.4 with argparse 1.1

**Comment by ThomasWaldmann** [comment]
https://github.com/ThomasWaldmann/argparse/blob/master/README.txt
