### ISSUE TITLE
argparse ArgumentParser(allow_abbrev=True) not documented on web

### ISSUE THREAD

**Issue by jrbrearley** [ThomasWaldmann/argparse#99]
The docs at https://argparse.readthedocs.io/en/latest/index.html do not appear to document the option  ArgumentParser(allow_abbrev=True). I found this in the command line help: help(argparse)

This is a very useful option to allow for less command line typing. Please document it to make its existence more widely known.

**Comment by ThomasWaldmann** [comment]
https://github.com/ThomasWaldmann/argparse/blob/master/README.txt
